name: Deploy to Server
on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout repository 
        uses: actions/checkout@v3

      - name: Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTHKEY }}

      - name: Set up SSH
        run: |
          #mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ./id_rsa_ansible_new
          chmod 600 ./id_rsa_ansible_new
          #ssh-keyscan -H 100.114.136.8 >> ~/.ssh/known_hosts

      - name: Test SSH Connection
        run: ssh -i ./id_rsa_ansible_new -o StrictHostKeyChecking=no sergey@100.114.136.8 "echo 'SSH Connection Successful'"

      - name: Copy project files to the server
        run: |
          sudo scp -i ./id_rsa_ansible_new -r ./assignment_3 sergey@100.114.136.8:/home/sergey/

      - name: Set up Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Run Ansible Playbook
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
        run: |
          ansible-playbook -i inventory.ini ansible-playbook.yml --private-key ./id_rsa_ansible -e "ansible_host_key_checking=False"
