name: Deploy to Server
on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout repository 
        uses: actions/checkout@v3

      - name: Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTHKEY }}

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 100.114.136.8 >> ~/.ssh/known_hosts


      - name: Set up Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Run Ansible Playbook
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
        run: |
          ansible-playbook -i inventory.ini ansible-playbook.yml --private-key ~/.ssh/id_rsa_ansible
